### ISSUE TITLE
Maybe Actually Read the GPLv3?

### ISSUE THREAD

**Issue by dylhack** [vapouryh/ssh-login-monitor#1]
https://github.com/vapouryh/ssh-login-monitor/blob/3fd6a7a3f6cae9af682c01471535d205186604ee/LICENSE#L634-L635
https://github.com/vapouryh/ssh-login-monitor/blob/3fd6a7a3f6cae9af682c01471535d205186604ee/LICENSE#L655-L658

**Comment by vapouryh** [comment]
Thanks for your issue, this has been resolved.
